### ISSUE TITLE
Only old versions of Faust will work

### ISSUE THREAD

**Issue by mxa** [chairaudio/SaM-Designer#2]
For unknown reasons with an updated version of Faust you will get the error `physicalmodeling.lib : 67 : ERROR : syntax error, unexpected ENABLE, expecting RBRAQ or IDENT` when exporting from Synth-A-Modeler to a puredata binary. Maybe @agraef or @eberdahl know more about this.

**Comment by rmichon** [comment]
We made some pretty significant modifications to the way the Faust libraries work about 2 years ago and it possible that this broke something in `physicalmodeling.lib`. Do you have a link to this file so that I can quickly check its content?

**Comment by mxa** [comment]
@rmichon yes, it's here: https://github.com/eberdahl/SaM/blob/8b66ec5311434e7e88c66ec161ae16cd04eb684e/physicalmodeling.lib

**Comment by rmichon** [comment]
Yes, try to replace:
```
import("music.lib");
import("effect.lib");
```
with:
```
import("all.lib");
```
`music.lib` and `effect.lib` were deprecated a while ago and should not work anymore with the latest version of Faust. `all.lib` is a quick convenient to solve this type of issue. Let me know if that helped...

**Comment by mxa** [comment]
@rmichon I replaced those lines, updated to Faust version 2.5.21

when trying to make a binary From SaM I still get this error:

```
Output: make: Entering directory '/home/max/Code/SaM-Designer/SaM'
install -d puredatadir
make DEST='puredatadir/' ARCH='puredata.cpp' LIB='-I""/faust/' CXXFLAGS='-O3 -fpermissive -msse -msse2 -msse3 -ffast-math  ' -f Makefile.pdcompile
make[1]: Entering directory '/home/max/Code/SaM-Designer/SaM'
faust -a puredata.cpp -double pluck_a_resonator.dsp -o puredatadir/pluck_a_resonator.cpp
```
**physicalmodeling.lib : 66 : ERROR : syntax error, unexpected ENABLE, expecting RBRAQ or IDENT**
```
Makefile.pdcompile:71: recipe for target 'puredatadir/pluck_a_resonator.cpp' failed
make[1]: *** [puredatadir/pluck_a_resonator.cpp] Error 1
make[1]: Leaving directory '/home/max/Code/SaM-Designer/SaM'
Makefile:65: recipe for target 'puredata' failed
make: *** [puredata] Error 2
make: Leaving directory '/home/max/Code/SaM-Designer/SaM'
```

**Comment by mxa** [comment]
Solved with this change:

https://github.com/chairaudio/SaM/commit/24b606d18d48113bd3af188866e10d4d56557af1#diff-447c4547cdf1b0e6d1a529343065eca7L70

**Comment by rmichon** [comment]
I see... `enable` is now a primitive of the language (which has nothing to do with the `enable` declared in `physicalmodeling.lib`). Ha I see you just figured this out haha!
